### ISSUE TITLE
"Improve this Doc" link incorrect reference

### ISSUE THREAD

**Issue by VPeruS** [opentk/opentk.github.io#13]
Actual: https://github.com/opentk/opentk.github.io/blob/master/index.md/#L1
Expected: https://github.com/opentk/opentk.github.io/blob/master/index.md

**Comment by varon** [comment]
Good spot. Thanks @VPeruS !

**Comment by DylanFPS** [comment]
Fixed in [`e8060dc0`](https://github.com/opentk/opentk.github.io/commit/e8060dc0a4df974794d19e2c11f0ade0826772d5)
