### ISSUE TITLE
Website resources page: Broken links to all projects

### ISSUE THREAD

**Issue by cielsys** [opentk/opentk.github.io#6]
All of the project links at https://opentk.github.io/resources/ are at the old opentk.com site, which evidently does not exist any more. It would be helpful to conveniently review some example projects to evaluate OpenTK, and fixing these links would help.
Also having this page with all those broken links makes OpenTK seem abandoned.

**Comment by daerogami** [comment]
Ill take care of this after I'm finished with #9

**Comment by daerogami** [comment]
Just an update, I'm about half-way through the list getting updates to the projects or marking them as abandoned. I hope to have a PR up between this weekend and the next.

**Comment by DylanFPS** [comment]
Fixed in the new site
